package gui.entities.types;

public enum MoveType {
	FORWARD, BACK, RIGHT, LEFT, FORWARD_RIGHT, FORWARD_LEFT, BACK_RIGHT, BACK_LEFT, REGULAR, ILLIGAL, CASTLING_ON_LEFT, CASTLING_ON_RIGHT, PROMOTION, POSSIBLE_PROMOTION, EN_PASSANT_LEFT, EN_PASSANT_RIGHT;
}
