package game.entities.types;

public enum Condition {
	FIRST_MOVE, MOVE, ATTACK, BLOCK, CHECK, MATE, TEMPORARY, UNKNOWN, CASTLING_ON_LEFT, CASTLING_ON_RIGHT, PROMOTION, POSSIBLE_PROMOTION, EN_PASSANT_LEFT, EN_PASSANT_RIGHT;
}
